"use client";

/**
 * GitHub Octicons - Official GitHub icons for brand consistency
 * 
 * Use Octicons for GitHub-specific features, Lucide for generic UI elements
 * @see https://primer.style/octicons
 */

// Import commonly used Octicons
import {
  RepoIcon,
  GitBranchIcon,
  GitPullRequestIcon,
  IssueOpenedIcon,
  IssueClosedIcon,
  CheckCircleIcon,
  XCircleIcon,
  PersonIcon,
  PeopleIcon,
  OrganizationIcon,
  RocketIcon,
  ShieldCheckIcon,
  ShieldLockIcon,
  LockIcon,
  UnlockIcon,
  KeyIcon,
  CopilotIcon,
  SparkleIcon,
  StarIcon,
  StarFillIcon,
  HeartIcon,
  HeartFillIcon,
  CommentIcon,
  CommentDiscussionIcon,
  CodeIcon,
  CodeSquareIcon,
  TerminalIcon,
  CommandPaletteIcon,
  WorkflowIcon,
  PlayIcon,
  StopIcon,
  SyncIcon,
  CheckIcon,
  XIcon,
  AlertIcon,
  AlertFillIcon,
  InfoIcon,
  QuestionIcon,
  LightBulbIcon,
  BookIcon,
  BookmarkIcon,
  BookmarkFillIcon,
  FileIcon,
  FileCodeIcon,
  FileDiffIcon,
  FileDirectoryIcon,
  FileDirectoryFillIcon,
  FileZipIcon,
  DownloadIcon,
  UploadIcon,
  LinkIcon,
  LinkExternalIcon,
  MailIcon,
  MentionIcon,
  BellIcon,
  BellFillIcon,
  BellSlashIcon,
  ClockIcon,
  CalendarIcon,
  HistoryIcon,
  EyeIcon,
  EyeClosedIcon,
  SearchIcon,
  FilterIcon,
  SortAscIcon,
  SortDescIcon,
  KebabHorizontalIcon,
  GearIcon,
  PencilIcon,
  TrashIcon,
  CopyIcon,
  ShareIcon,
  GraphIcon,
  PulseIcon,
  TableIcon,
  ListOrderedIcon,
  ListUnorderedIcon,
  DashIcon,
  PlusIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  TriangleDownIcon,
  TriangleUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowSwitchIcon,
  HomeIcon,
  GlobeIcon,
  LocationIcon,
  PackageIcon,
  PackageDependentsIcon,
  PackageDependenciesIcon,
  VerifiedIcon,
  UnverifiedIcon,
  ZapIcon,
  FlameIcon,
  MilestoneIcon,
  TagIcon,
  GoalIcon,
  TrophyIcon,
  NorthStarIcon,
  MortarBoardIcon,
  type Icon as OcticonType,
} from "@primer/octicons-react";

// Re-export individual icons for direct use
export {
  RepoIcon,
  GitBranchIcon,
  GitPullRequestIcon,
  IssueOpenedIcon,
  IssueClosedIcon,
  CheckCircleIcon,
  XCircleIcon,
  PersonIcon,
  PeopleIcon,
  OrganizationIcon,
  RocketIcon,
  ShieldCheckIcon,
  ShieldLockIcon,
  LockIcon,
  UnlockIcon,
  KeyIcon,
  CopilotIcon,
  SparkleIcon,
  StarIcon,
  StarFillIcon,
  HeartIcon,
  HeartFillIcon,
  CommentIcon,
  CommentDiscussionIcon,
  CodeIcon,
  CodeSquareIcon,
  TerminalIcon,
  CommandPaletteIcon,
  WorkflowIcon,
  PlayIcon,
  StopIcon,
  SyncIcon,
  CheckIcon,
  XIcon,
  AlertIcon,
  AlertFillIcon,
  InfoIcon,
  QuestionIcon,
  LightBulbIcon,
  BookIcon,
  BookmarkIcon,
  BookmarkFillIcon,
  FileIcon,
  FileCodeIcon,
  FileDiffIcon,
  FileDirectoryIcon,
  FileDirectoryFillIcon,
  FileZipIcon,
  DownloadIcon,
  UploadIcon,
  LinkIcon,
  LinkExternalIcon,
  MailIcon,
  MentionIcon,
  BellIcon,
  BellFillIcon,
  BellSlashIcon,
  ClockIcon,
  CalendarIcon,
  HistoryIcon,
  EyeIcon,
  EyeClosedIcon,
  SearchIcon,
  FilterIcon,
  SortAscIcon,
  SortDescIcon,
  KebabHorizontalIcon,
  GearIcon,
  PencilIcon,
  TrashIcon,
  CopyIcon,
  ShareIcon,
  GraphIcon,
  PulseIcon,
  TableIcon,
  ListOrderedIcon,
  ListUnorderedIcon,
  DashIcon,
  PlusIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  TriangleDownIcon,
  TriangleUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowSwitchIcon,
  HomeIcon,
  GlobeIcon,
  LocationIcon,
  PackageIcon,
  PackageDependentsIcon,
  PackageDependenciesIcon,
  VerifiedIcon,
  UnverifiedIcon,
  ZapIcon,
  FlameIcon,
  MilestoneIcon,
  TagIcon,
  GoalIcon,
  TrophyIcon,
  NorthStarIcon,
  MortarBoardIcon,
};

// Semantic icon mappings for common use cases
export const Icons = {
  // GitHub Products & Features
  copilot: CopilotIcon,
  actions: WorkflowIcon,
  security: ShieldCheckIcon,
  packages: PackageIcon,
  pullRequest: GitPullRequestIcon,
  issue: IssueOpenedIcon,
  repo: RepoIcon,
  branch: GitBranchIcon,
  code: CodeIcon,
  
  // User & Org
  user: PersonIcon,
  users: PeopleIcon,
  org: OrganizationIcon,
  
  // Status & State
  success: CheckCircleIcon,
  error: XCircleIcon,
  warning: AlertIcon,
  info: InfoIcon,
  
  // Navigation
  home: HomeIcon,
  search: SearchIcon,
  settings: GearIcon,
  
  // Actions
  add: PlusIcon,
  edit: PencilIcon,
  delete: TrashIcon,
  copy: CopyIcon,
  share: ShareIcon,
  download: DownloadIcon,
  upload: UploadIcon,
  link: LinkIcon,
  externalLink: LinkExternalIcon,
  
  // Data & Charts
  graph: GraphIcon,
  pulse: PulseIcon,
  table: TableIcon,
  
  // Learning & Achievements
  learn: MortarBoardIcon,
  book: BookIcon,
  goal: GoalIcon,
  trophy: TrophyIcon,
  star: StarIcon,
  milestone: MilestoneIcon,
  rocket: RocketIcon,
  sparkle: SparkleIcon,
  zap: ZapIcon,
  flame: FlameIcon,
  
  // Misc
  notification: BellIcon,
  mail: MailIcon,
  clock: ClockIcon,
  calendar: CalendarIcon,
  eye: EyeIcon,
  filter: FilterIcon,
  tag: TagIcon,
  verified: VerifiedIcon,
} as const;

export type IconName = keyof typeof Icons;

// Export type for use in components
export type { OcticonType };
